const countryCodes = {
  kr: '대한민국 (Korea, Republic of)',
  af: '아프가니스탄 (Afghanistan)',
  ax: '올란드 제도 (Åland Islands)',
  al: '알바니아 (Albania)',
  dz: '알제리 (Algeria)',
  as: '아메리칸사모아 (American Samoa)',
  ad: '안도라 (Andorra)',
  ao: '앙골라 (Angola)',
  ai: '앵귈라 (Anguilla)',
  aq: '남극 (Antarctica)',
  ag: '앤티가 바부다 (Antigua and Barbuda)',
  ar: '아르헨티나 (Argentina)',
  am: '아르메니아 (Armenia)',
  aw: '아루바 (Aruba)',
  au: '오스트레일리아 (Australia)',
  at: '오스트리아 (Austria)',
  az: '아제르바이잔 (Azerbaijan)',
  bs: '바하마 (Bahamas)',
  bh: '바레인 Bahrain)',
  bd: '방글라데시 (Bangladesh)',
  bb: '바베이도스 (Barbados)',
  by: '벨라루스 (Belarus)',
  be: '벨기에 (Belgium)',
  bz: '벨리즈 (Belize)',
  bj: '베냉 (Benin)',
  bm: '버뮤다 (Bermuda)',
  bt: '부탄 (Bhutan)',
  bo: '볼리비아 (Bolivia (Plurinational State of))',
  bq: '보네르섬 (Bonaire, Sint Eustatius and Saba)',
  ba: '보스니아 헤르체고비나 (Bosnia and Herzegovina)',
  bw: '보츠와나 (Botswana)',
  bv: '부베섬 (Bouvet Island)',
  br: '브라질 (Brazil)',
  io: '영국령 인도양 지역 (British Indian Ocean Territory)',
  bn: '브루나이 (Brunei Darussalam)',
  bg: '불가리아 (Bulgaria)',
  bf: '부르키나파소 (Burkina Faso)',
  bi: '부룬디 (Burundi)',
  kh: '캄보디아 (Cambodia)',
  cm: '카메룬 (Cameroon)',
  ca: '캐나다 (Canada)',
  cv: '카보베르데 (Cabo Verde)',
  ky: '케이맨 제도 (Cayman Islands)',
  cf: '중앙아프리카 공화국 (Central African Republic)',
  td: '차드 (Chad)',
  cl: '칠레 (Chile)',
  cn: '중국 (China)',
  cx: '크리스마스섬 (Christmas Island)',
  cc: '코코스 제도 (Cocos (Keeling) Islands)',
  co: '콜롬비아 (Colombia)',
  km: '코모로 (Comoros)',
  cg: '콩고 공화국 (Congo)',
  cd: '콩고 민주 공화국 (Congo, Democratic Republic of the)',
  ck: '쿡 제도 (Cook Islands)',
  cr: '코스타리카 (Costa Rica)',
  ci: "코트디부아르 (Côte d'Ivoire)",
  hr: '크로아티아 (Croatia)',
  cu: '쿠바 (Cuba)',
  cw: '퀴라소 (Curaçao)',
  cy: '키프로스 (Cyprus)',
  cz: '체코 (Czechia)',
  dk: '덴마크 (Denmark)',
  dj: '지부티 (Djibouti)',
  dm: '도미니카 연방 (Dominica)',
  do: '도미니카 공화국 (Dominican Republic)',
  ec: '에콰도르 (Ecuador)',
  eg: '이집트 (Egypt)',
  sv: '엘살바도르 (El Salvador)',
  gq: '적도 기니 (Equatorial Guinea)',
  er: '에리트레아 (Eritrea)',
  ee: '에스토니아 (Estonia)',
  et: '에티오피아 (Ethiopia)',
  fk: '포클랜드 제도 (Falkland Islands (Malvinas))',
  fo: '페로 제도 (Faroe Islands)',
  fj: '피지 (Fiji)',
  fi: '핀란드 (Finland)',
  fr: '프랑스 (France)',
  gf: '프랑스령 기아나 (French Guiana)',
  pf: '프랑스령 폴리네시아 (French Polynesia)',
  tf: '프랑스령 남방 및 남극 지역 (French Southern Territories)',
  ga: '가봉 (Gabon)',
  gm: '감비아 (Gambia)',
  ge: '조지아 (Georgia)',
  de: '독일 (Germany)',
  gh: '가나 (Ghana)',
  gi: '지브롤터 (Gibraltar)',
  gr: '그리스 (Greece)',
  gl: '그린란드 (Greenland)',
  gd: '그레나다 (Grenada)',
  gp: '과들루프 (Guadeloupe)',
  gu: '괌 (Guam)',
  gt: '과테말라 (Guatemala)',
  gg: '건지섬 (Guernsey)',
  gn: '기니 (Guinea)',
  gw: '기니비사우 (Guinea-Bissau)',
  gy: '가이아나 (Guyana)',
  ht: '아이티 (Haiti)',
  hm: '허드 맥도널드 제도 (Heard Island and McDonald Islands)',
  va: '바티칸 시국 (Holy See)',
  hn: '온두라스 (Honduras)',
  hk: '홍콩 (Hong Kong)',
  hu: '헝가리 (Hungary)',
  is: '아이슬란드 (Iceland)',
  in: '인도 (India)',
  id: '인도네시아 (Indonesia)',
  ir: '이란 (Iran (Islamic Republic of))',
  iq: '이라크 (Iraq)',
  ie: '아일랜드 (Ireland)',
  im: '맨섬 (Isle of Man)',
  il: '이스라엘 (Israel)',
  it: '이탈리아 (Italy)',
  jm: '자메이카 (Jamaica)',
  jp: '일본 (Japan)',
  je: '저지섬 (Jersey)',
  jo: '요르단 (Jordan)',
  kz: '카자흐스탄 (Kazakhstan)',
  ke: '케냐 (Kenya)',
  ki: '키리바시 (Kiribati)',
  kw: '쿠웨이트 (Kuwait)',
  kg: '키르기스스탄 (Kyrgyzstan)',
  la: "라오스 (Lao People's Democratic Republic)",
  lv: '라트비아 (Latvia)',
  lb: '레바논 (Lebanon)',
  ls: '레소토 (Lesotho)',
  lr: '라이베리아 (Liberia)',
  ly: '리비아 (Libya)',
  li: '리히텐슈타인 (Liechtenstein)',
  lt: '리투아니아 (Lithuania)',
  lu: '룩셈부르크 (Luxembourg)',
  mo: '마카오 (Macao)',
  mk: '북마케도니아 (North Macedonia)',
  mg: '마다가스카르 (Madagascar)',
  mw: '말라위 (Malawi)',
  my: '말레이시아 (Malaysia)',
  mv: '몰디브 (Maldives)',
  ml: '말리 (Mali)',
  mt: '몰타 (Malta)',
  mh: '마셜 제도 (Marshall Islands)',
  mq: '마르티니크 (Martinique)',
  mr: '모리타니 (Mauritania)',
  mu: '모리셔스 (Mauritius)',
  yt: '마요트 (Mayotte)',
  mx: '멕시코 (Mexico)',
  fm: '미크로네시아 연방 (Micronesia (Federated States of))',
  ma: '모로코 (Morocco)',
  md: '몰도바 (Moldova, Republic of)',
  mc: '모나코 (Monaco)',
  mn: '몽골 (Mongolia)',
  me: '몬테네그로 (Montenegro)',
  ms: '몬트세랫 (Montserrat)',
  mz: '모잠비크 (Mozambique)',
  mm: '미얀마 (Myanmar)',
  na: '나미비아 (Namibia)',
  nr: '나우루 (Nauru)',
  np: '네팔 (Nepal)',
  nl: '네덜란드 (Netherlands)',
  nc: '누벨칼레도니 (New Caledonia)',
  nz: '뉴질랜드 (New Zealand)',
  ni: '니카라과 (Nicaragua)',
  ne: '니제르 (Niger)',
  ng: '나이지리아 (Nigeria)',
  nu: '니우에 (Niue)',
  nf: '노퍽섬 (Norfolk Island)',
  mp: '북마리아나 제도 (Northern Mariana Islands)',
  no: '노르웨이 (Norway)',
  om: '오만 (Oman)',
  pk: '파키스탄 (Pakistan)',
  pw: '팔라우 (Palau)',
  ps: '팔레스타인 (Palestine, State of)',
  pa: '파나마 (Panama)',
  pg: '파푸아뉴기니 (Papua New Guinea)',
  py: '파라과이 (Paraguay)',
  pe: '페루 (Peru)',
  ph: '필리핀 (Philippines)',
  pn: '핏케언 제도 (Pitcairn)',
  pl: '폴란드 (Poland)',
  pt: '포르투갈 (Portugal)',
  pr: '푸에르토리코 (Puerto Rico)',
  qa: '카타르 (Qatar)',
  re: '레위니옹 (Réunion)',
  ro: '루마니아 (Romania)',
  ru: '러시아 (Russian Federation)',
  rw: '르완다 (Rwanda)',
  bl: '생바르텔레미 (Saint Barthélemy)',
  sh: '세인트헬레나 (Saint Helena, Ascension and Tristan da Cunha)',
  kn: '세인트키츠 네비스 (Saint Kitts and Nevis)',
  lc: '세인트루시아 (Saint Lucia)',
  mf: '생마르탱 (Saint Martin (French part))',
  pm: '생피에르 미클롱 (Saint Pierre and Miquelon)',
  vc: '세인트빈센트 그레나딘 (Saint Vincent and the Grenadines)',
  ws: '사모아 (Samoa)',
  sm: '산마리노 (San Marino)',
  st: '상투메 프린시페 (Sao Tome and Principe)',
  sa: '사우디아라비아 (Saudi Arabia)',
  sn: '세네갈 (Senegal)',
  rs: '세르비아 (Serbia)',
  sc: '세이셸 (Seychelles)',
  sl: '시에라리온 (Sierra Leone)',
  sg: '싱가포르 (Singapore)',
  sx: '신트마르턴 (Sint Maarten (Dutch part))',
  sk: '슬로바키아 (Slovakia)',
  si: '슬로베니아 (Slovenia)',
  sb: '솔로몬 제도 (Solomon Islands)',
  so: '소말리아 (Somalia)',
  za: '남아프리카 공화국 (South Africa)',
  gs: '사우스조지아 사우스샌드위치 제도 (South Georgia and the South Sandwich Islands)',
  ss: '남수단 (South Sudan)',
  es: '스페인 (Spain)',
  lk: '스리랑카 (Sri Lanka)',
  sd: '수단 (Sudan)',
  sr: '수리남 (Suriname)',
  sj: '스발바르 얀마옌 (Svalbard and Jan Mayen)',
  sz: '에스와티니 (Eswatini)',
  se: '스웨덴 (Sweden)',
  ch: '스위스 (Switzerland)',
  sy: '시리아 (Syrian Arab Republic)',
  tw: '대만 (Taiwan)',
  tj: '타지키스탄 (Tajikistan)',
  tz: '탄자니아 (Tanzania, United Republic of)',
  th: '태국 (Thailand)',
  tl: '동티모르 (Timor-Leste)',
  tg: '토고 (Togo)',
  tk: '토켈라우 (Tokelau)',
  to: '통가 (Tonga)',
  tt: '트리니다드 토바고 (Trinidad and Tobago)',
  tn: '튀니지 (Tunisia)',
  tr: '튀르키예 (Türkiye, Republic of)',
  tm: '투르크메니스탄 (Turkmenistan)',
  tc: '터크스 케이커스 제도 (Turks and Caicos Islands)',
  tv: '투발루 (Tuvalu)',
  ug: '우간다 (Uganda)',
  ua: '우크라이나 (Ukraine)',
  ae: '아랍에미리트 (United Arab Emirates)',
  gb: '영국 (United Kingdom of Great Britain and Northern Ireland)',
  us: '미국 (United States of America)',
  um: '미국령 군소 제도 (United States Minor Outlying Islands)',
  uy: '우루과이 (Uruguay)',
  uz: '우즈베키스탄 (Uzbekistan)',
  vu: '바누아투 (Vanuatu)',
  ve: '베네수엘라 (Venezuela (Bolivarian Republic of))',
  vn: '베트남 (Viet Nam)',
  vg: '영국령 버진아일랜드 (Virgin Islands (British))',
  vi: '미국령 버진아일랜드 (Virgin Islands (U.S.))',
  wf: '왈리스 푸투나 (Wallis and Futuna)',
  eh: '서사하라 (Western Sahara)',
  ye: '예멘 (Yemen)',
  zm: '잠비아 (Zambia)',
  zw: '짐바브웨 (Zimbabwe)',
};

export default countryCodes;
